/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeckAnalyzerRouteImport } from './routes/deck-analyzer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckAnalyzerRoute = DeckAnalyzerRouteImport.update({
  id: '/deck-analyzer',
  path: '/deck-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck-analyzer': typeof DeckAnalyzerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck-analyzer': typeof DeckAnalyzerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck-analyzer': typeof DeckAnalyzerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deck-analyzer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deck-analyzer'
  id: '__root__' | '/' | '/deck-analyzer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckAnalyzerRoute: typeof DeckAnalyzerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck-analyzer': {
      id: '/deck-analyzer'
      path: '/deck-analyzer'
      fullPath: '/deck-analyzer'
      preLoaderRoute: typeof DeckAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckAnalyzerRoute: DeckAnalyzerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
